//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBites
{
    public partial class _Default
    {
        protected global::System.Web.UI.WebControls.TextBox txtName;

        protected global::System.Web.UI.WebControls.TextBox txtComment;

        protected global::System.Web.UI.WebControls.DropDownList ddlRating;

        protected global::System.Web.UI.WebControls.Button btnSubmitFeedback;

        protected global::System.Web.UI.WebControls.Label lblStatus;

        protected global::System.Web.UI.WebControls.Repeater rptFeedbacks;
    }
}
